FROM python:3.10-slim

# Evita que Python genere archivos .pyc y fuerza a que la salida de consola sea inmediata
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

# (Opcional) Instala dependencias del sistema necesarias para PostgreSQL
RUN apt-get update && apt-get install -y libpq-dev gcc

COPY requirements.txt .
# Si aún no tienes un requirements.txt, esto no fallará si creas uno vacío
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]