# Generated by Django 5.2.7 on 2025-10-24 22:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Movimiento')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'movimientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Tarea')),
                ('bloqueado', models.BooleanField(default=False, verbose_name='Bloqueado')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='saga.movimiento', verbose_name='Movimiento')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'tareas',
                'ordering': ['movimiento', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=10, unique=True, verbose_name='Folio')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('cliente_id', models.IntegerField(verbose_name='ID Cliente')),
                ('cliente_nombre', models.CharField(max_length=255, verbose_name='Nombre del Cliente')),
                ('agente_id', models.IntegerField(blank=True, null=True, verbose_name='ID Agente')),
                ('agente_nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre del Agente')),
                ('beneficiario_id', models.IntegerField(blank=True, null=True, verbose_name='ID Beneficiario')),
                ('beneficiario_nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre del Beneficiario')),
                ('afianzadora_id', models.IntegerField(blank=True, null=True, verbose_name='ID Afianzadora')),
                ('afianzadora_nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre de la Afianzadora')),
                ('tipo_proceso', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Proceso')),
                ('programa_proveedores', models.BooleanField(default=False, verbose_name='Programa de Proveedores')),
                ('numero_fianza', models.CharField(blank=True, max_length=50, verbose_name='Número de Fianza')),
                ('prima_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prima Inicial')),
                ('prima_futura', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prima Futura')),
                ('prima_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prima Total')),
                ('importe_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Importe Total')),
                ('estatus', models.CharField(choices=[('EN REVISIÓN DE DOCUMENTOS', 'EN REVISIÓN DE DOCUMENTOS'), ('EN REVISIÓN DE PREVIAS', 'EN REVISIÓN DE PREVIAS'), ('EN PROCESO/C.N.S.', 'EN PROCESO/C.N.S.'), ('EN PROCESO/CANCELACIÓN', 'EN PROCESO/CANCELACIÓN'), ('EN PROCESO/C.T.T.', 'EN PROCESO/C.T.T.'), ('EN PROCESO/ACT EF', 'EN PROCESO/ACT EF'), ('EN PROCESO/ACT CLG', 'EN PROCESO/ACT CLG'), ('EN PROCESO/OTROS', 'EN PROCESO/OTROS'), ('NO PROCEDE', 'NO PROCEDE'), ('PENDIENTE/C.N.S.', 'PENDIENTE/C.N.S.'), ('PENDIENTE/CANCELACIÓN', 'PENDIENTE/CANCELACIÓN'), ('PENDIENTE/C.T.T.', 'PENDIENTE/C.T.T.'), ('PENDIENTE/ACT EF', 'PENDIENTE/ACT EF'), ('PENDIENTE/ACT CLG', 'PENDIENTE/ACT CLG'), ('PENDIENTE/OTROS', 'PENDIENTE/OTROS'), ('TERMINADO', 'TERMINADO'), ('TERMINADO/COMPROMISO', 'TERMINADO/COMPROMISO'), ('TERMINADO/PENDIENTE', 'TERMINADO/PENDIENTE')], default='EN REVISIÓN DE DOCUMENTOS', max_length=50, verbose_name='Estatus')),
                ('fecha_termino', models.DateField(blank=True, null=True, verbose_name='Fecha de Término')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('estatus_pago', models.CharField(choices=[('SE MANDÓ RECIBO', 'SE MANDÓ RECIBO'), ('NO PAGADA', 'NO PAGADA'), ('PENDIENTE', 'PENDIENTE')], default='PENDIENTE', max_length=50, verbose_name='Estatus de Pago')),
                ('observaciones_pago', models.CharField(blank=True, max_length=255, verbose_name='Observaciones de Pago')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramites', to='saga.movimiento', verbose_name='Movimiento')),
            ],
            options={
                'verbose_name': 'Trámite',
                'verbose_name_plural': 'Trámites',
                'db_table': 'tramites',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ObservacionTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(max_length=255, verbose_name='Observación')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='saga.tramite', verbose_name='Trámite')),
            ],
            options={
                'verbose_name': 'Observación del Trámite',
                'verbose_name_plural': 'Observaciones de Trámites',
                'db_table': 'observaciones_tramites',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=255, verbose_name='Nombre de la Persona')),
                ('categoria', models.CharField(choices=[('BC-AFIANZADORA', 'BC-AFIANZADORA'), ('CLIENTES-AFIANZADORA', 'CLIENTES-AFIANZADORA'), ('CLIENTES-BC', 'CLIENTES-BC')], max_length=50, verbose_name='Categoría')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('fecha_completado', models.DateField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('creado_por', models.CharField(max_length=255, verbose_name='Creado Por')),
                ('completado_por', models.CharField(blank=True, max_length=255, verbose_name='Completado Por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromisos', to='saga.tramite', verbose_name='Trámite')),
            ],
            options={
                'verbose_name': 'Compromiso',
                'verbose_name_plural': 'Compromisos',
                'db_table': 'compromisos',
                'ordering': ['fecha_vencimiento', '-completado'],
            },
        ),
        migrations.CreateModel(
            name='TramiteTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('fecha_completado', models.DateField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tramite_tareas', to='saga.tarea', verbose_name='Tarea')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramite_tareas', to='saga.tramite', verbose_name='Trámite')),
            ],
            options={
                'verbose_name': 'Tarea del Trámite',
                'verbose_name_plural': 'Tareas del Trámite',
                'db_table': 'tramite_tareas',
                'ordering': ['tramite', 'tarea'],
            },
        ),
        migrations.AddIndex(
            model_name='tramite',
            index=models.Index(fields=['folio'], name='tramites_folio_0381a4_idx'),
        ),
        migrations.AddIndex(
            model_name='tramite',
            index=models.Index(fields=['cliente_id'], name='tramites_cliente_c8eddf_idx'),
        ),
        migrations.AddIndex(
            model_name='tramite',
            index=models.Index(fields=['estatus'], name='tramites_estatus_ba73c5_idx'),
        ),
        migrations.AddIndex(
            model_name='tramite',
            index=models.Index(fields=['fecha'], name='tramites_fecha_7a2b10_idx'),
        ),
        migrations.AddIndex(
            model_name='compromiso',
            index=models.Index(fields=['tramite', 'completado'], name='compromisos_tramite_be9560_idx'),
        ),
        migrations.AddIndex(
            model_name='compromiso',
            index=models.Index(fields=['fecha_vencimiento'], name='compromisos_fecha_v_6e1d2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tramitetarea',
            unique_together={('tramite', 'tarea')},
        ),
    ]
