# Generated by Django 5.2.7 on 2025-10-29 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Estatus del tramite')),
            ],
            options={
                'verbose_name': 'Estatus',
                'verbose_name_plural': 'Estatus',
                'db_table': 'estatus',
                'ordering': ['nombre'],
            },
        ),
        migrations.RenameIndex(
            model_name='tramite',
            new_name='tramites_estatus_bb77f6_idx',
            old_name='tramites_estatus_ba73c5_idx',
        ),
        migrations.AlterField(
            model_name='tramite',
            name='estatus_pago',
            field=models.CharField(choices=[('SE MANDÓ RECIBO', 'SE MANDÓ RECIBO'), ('NO PAGADA', 'NO PAGADA'), ('PAGADA', 'PAGADA'), ('PENDIENTE', 'PENDIENTE')], default='PENDIENTE', max_length=50, verbose_name='Estatus de Pago'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='estatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramites', to='saga.estatus', verbose_name='estatus'),
        ),
    ]
