# Generated by Django 5.2.7 on 2025-10-29 21:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saga', '0002_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='agente_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Agente'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='estatus_pago',
            field=models.CharField(choices=[('SE MANDÓ RECIBO', 'SE MANDÓ RECIBO'), ('NO PAGADA', 'NO PAGADA'), ('PAGADA', 'PAGADA'), ('PENDIENTE', 'PENDIENTE')], default='PENDIENTE', max_length=50, null=True, verbose_name='Estatus de Pago'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='importe_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Importe Total'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='numero_fianza',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Fianza'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='observaciones_pago',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observaciones de Pago'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='prima_futura',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prima Futura'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='prima_inicial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prima Inicial'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='prima_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prima Total'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='programa_proveedores',
            field=models.BooleanField(default=False, null=True, verbose_name='Programa de Proveedores'),
        ),
    ]
