# Generated by Django 5.2.7 on 2025-10-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saga', '0003_alter_tramite_agente_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='estatus_pago',
            field=models.CharField(choices=[('SE MANDÓ RECIBO', 'SE MANDÓ RECIBO'), ('NO PAGADA', 'NO PAGADA'), ('PAGADA', 'PAGADA'), ('PENDIENTE', 'PENDIENTE'), ('NO APLICA', 'NO APLICA')], default='PENDIENTE', max_length=50, null=True, verbose_name='Estatus de Pago'),
        ),
    ]
