# Generated by Django 5.2.7 on 2025-11-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saga', '0004_alter_tramite_estatus_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='creado_por',
            field=models.CharField(blank=True, max_length=100, verbose_name='Creado Por'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='estatus_pago',
            field=models.CharField(choices=[('SE MANDÓ RECIBO', 'SE MANDÓ RECIBO'), ('NO PAGADA', 'NO PAGADA'), ('PAGADA', 'PAGADA'), ('PENDIENTE', 'PENDIENTE')], default='PENDIENTE', max_length=50, null=True, verbose_name='Estatus de Pago'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='folio',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Folio'),
        ),
    ]
