# Generated by Django 5.2.7 on 2025-12-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saga', '0005_tramite_creado_por_alter_tramite_estatus_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observaciontramite',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
    ]
