# Generated by Django 5.2.7 on 2026-01-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saga', '0006_alter_observaciontramite_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observaciontramite',
            name='observacion',
            field=models.TextField(verbose_name='Observación'),
        ),
    ]
