# Generated by Django 5.2.7 on 2026-01-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saga', '0007_alter_observaciontramite_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='cliente_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Cliente'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Cliente'),
        ),
    ]
