# Generated by Django 5.2.7 on 2026-01-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saga', '0008_alter_tramite_cliente_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='tipo_proceso',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Proceso'),
        ),
    ]
