# Generated by Django 5.2.7 on 2026-01-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saga', '0009_alter_tramite_tipo_proceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='afianzadora_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la Afianzadora'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='beneficiario_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Beneficiario'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
    ]
