# Generated by Django 5.2.7 on 2026-01-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saga', '0010_alter_tramite_afianzadora_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='creado_por',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Creado Por'),
        ),
    ]
