# Generated by Django 5.2.7 on 2026-01-06 20:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saga', '0011_alter_tramite_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='importe_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Importe Total'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='prima_futura',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Prima Futura'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='prima_inicial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Prima Inicial'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='prima_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Prima Total'),
        ),
    ]
