# Generated by Django 5.2.7 on 2026-07-27 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saga', '0014_seed_ramos_tipos_fianza'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfianzadoraLegacy',
            fields=[
                ('id_afi', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_afi', models.CharField(max_length=255)),
                ('meta', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('afianzadora', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Afianzadora Legacy',
                'db_table': 'afianzadoras',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='tramite',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Emisión'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='estatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramites', to='saga.estatus', verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='estatus_pago',
            field=models.CharField(choices=[('SE MANDÓ RECIBO', 'SE MANDÓ RECIBO'), ('NO PAGADA', 'NO PAGADA'), ('PAGADA', 'PAGADA'), ('PENDIENTE', 'PENDIENTE'), ('NO APLICA', 'NO APLICA')], default='PENDIENTE', max_length=50, null=True, verbose_name='Estatus de Pago'),
        ),
    ]
